#
# Makefile -- build images for matrixoptik
#
# (c) 2019 Prof Dr Andreas Müller, Hochschule Rapperswil
#
all:	snellius.pdf ray.pdf curve.pdf abb.pdf fl.pdf achr.pdf solution.pdf

snellius.pdf:	snellius.tex
	pdflatex snellius.tex

ray.pdf:	ray.tex
	pdflatex ray.tex

curve.pdf:	curve.tex
	pdflatex curve.tex

abb.pdf:	abb.tex
	pdflatex abb.tex

fl.pdf:	fl.tex
	pdflatex fl.tex

achr.pdf:	achr.tex
	pdflatex achr.tex

solution.pdf:	solution.tex
	pdflatex solution.tex
