#
# Makefile -- graphische Darstellung für Aufgabe 30000044
#
# (c) 2016 Prof Dr Andreas Mueller, Hochschule Rapperswil
#
all:

images:	graph-1.pdf

graph-1.pdf:	graph.mp
	TEX=latex mpost graph.mp
	mptopdf graph.1
