#
# Makefile -- build images
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
all:	am.pdf lissajous.pdf spiegelung.pdf filter.pdf konstellation.pdf \
	sep.pdf psk.pdf detektor.pdf

am.pdf:	am.tex
	pdflatex am.tex

lissajous.pdf:	lissajous.tex
	pdflatex lissajous.tex

spiegelung.pdf:	spiegelung.tex
	pdflatex spiegelung.tex

filter.pdf:	filter.tex
	pdflatex filter.tex

konstellation.pdf:	konstellation.tex
	pdflatex konstellation.tex

sep.pdf:	sep.tex
	pdflatex sep.tex

psk.pdf:	psk.tex
	pdflatex psk.tex

detektor.pdf:	detektor.tex
	pdflatex detektor.tex

