#
# Makefile -- Abbildungen
#
# (c) 2018 Prof Dr Andreas Müller, Hochschule Rapperswil
#
images:	strahlensatz.pdf brennweite.pdf

strahlensatz.pdf:	strahlensatz.tex
	pdflatex strahlensatz.tex

brennweite.pdf:	brennweite.tex
	pdflatex brennweite.tex

