#
# Makefile -- Abbildungen
#
# (c) 2018 Prof Dr Andreas Müller, Hochschule Rapperswil
#
images:	strahlensatz.pdf brennweite.pdf kamera.pdf kameraprinzip.pdf	\
	lochkamera.pdf

strahlensatz.pdf:	strahlensatz.tex
	pdflatex strahlensatz.tex

brennweite.pdf:	brennweite.tex
	pdflatex brennweite.tex

kamera.pdf:	kamera.tex camera.png objektiv.png
	pdflatex kamera.tex

kameraprinzip.pdf:	kameraprinzip.tex
	pdflatex kameraprinzip.tex

lochkamera.pdf:	lochkamera.tex
	pdflatex lochkamera.tex

