#
# Makefile -- build Morley triangle image
#
# (c) 2015 Prof Dr Andreas Mueller, Hochschule Rapperswil
#
all:

images:	morley-1.pdf

morley-1.pdf:	morley.mp
	TEX=latex mpost morley.mp
	mptopdf morley.1
