#
# Makefile -- build images
#
# (c) 2018 Prof Dr Andreas Müller, Hochschule Rapperswil
#
images:	flussdiagrammLoesungsmenge.pdf

flussdiagrammLoesungsmenge.pdf:	flussdiagrammLoesungsmenge.tex
	pdflatex flussdiagrammLoesungsmenge.tex

