#
# Makefile -- build images
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
all:	am.pdf lissajous.pdf spiegelung.pdf filter.pdf konstellation.pdf

am.pdf:	am.tex
	pdflatex am.tex

lissajous.pdf:	lissajous.tex
	pdflatex lissajous.tex

spiegelung.pdf:	spiegelung.tex
	pdflatex spiegelung.tex

filter.pdf:	filter.tex
	pdflatex filter.tex

konstellation.pdf:	konstellation.tex
	pdflatex konstellation.tex

