#
# Makefile -- build images
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
all:	am.pdf lissajous.pdf

am.pdf:	am.tex
	pdflatex am.tex

lissajous.pdf:	lissajous.tex
	pdflatex lissajous.tex

